# docker-compose.yml

version: '3'

services:
  redis:
    container_name: redis
    image: redis:5.0.6-alpine
    networks:
      - main
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  db-server:
    restart: always
    image: postgres:latest
    container_name: db-server
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=qsystem_sa
      - POSTGRES_PASSWORD=pAssw0rd!
      - POSTGRES_DB=qsystem_db
    networks:
      - main
    volumes:
      - pgdata:/var/lib/postgresql/qsystem_db/

  web-server:
    build:
      context: ./src/web
    links:
      - db-server:postgres
    networks:
      - main
    volumes:
      # - web-django:/usr/src/app
      - web-static:/staticfiles
      - web-media:/media
    command: gunicorn qsystem.wsgi:application -w 2 -b :8001
    container_name: web-server
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - 8001:8001


#  play-server:
#    build:
#      context: ./src/play
#    networks:
#      - main
#    #command: python callQ.py
#    container_name: play-server
#    depends_on:
#      - redis
    

volumes:  
  redis_data:
  web-static:
  web-media:
  pgdata:


networks:
  main: