# Generated by Django 2.1.5 on 2019-07-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='slug',
        ),
    ]
