# Generated by Django 2.1.5 on 2019-08-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_section_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
