# Generated by Django 3.0.5 on 2020-08-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0006_auto_20200803_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['seq']},
        ),
        migrations.AddField(
            model_name='section',
            name='seq',
            field=models.IntegerField(default=10),
        ),
    ]
