# Generated by Django 3.0.5 on 2021-03-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0007_auto_20200810_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='print_qty',
            field=models.IntegerField(default=1),
        ),
    ]
