# Generated by Django 2.1.5 on 2019-07-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='counter_number',
            field=models.IntegerField(default=0),
        ),
    ]
