# Generated by Django 2.1.5 on 2019-07-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_counter_counter_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='current_number',
        ),
    ]
