# Generated by Django 2.1.5 on 2019-07-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_remove_counter_current_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='slug',
        ),
    ]
