# Generated by Django 3.0.5 on 2020-07-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_remove_counter_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={'ordering': ['counter_number']},
        ),
        migrations.AddField(
            model_name='counter',
            name='current_job',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='counter',
            index=models.Index(fields=['name'], name='idx_counter_counter_name'),
        ),
    ]
