# Generated by Django 3.0.5 on 2020-07-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_auto_20200731_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='current_job',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
