# Generated by Django 3.0.5 on 2020-07-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_started_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='job',
            name='on_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['counter'], name='idx_job_job_counter'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['section'], name='idx_job_job_section'),
        ),
    ]
