# Generated by Django 3.0.5 on 2021-01-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20210121_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_archive',
            name='day_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job_archive',
            name='day_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job_archive',
            name='hour_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job_archive',
            name='hour_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job_archive',
            name='month_arch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job_archive',
            name='process_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job_archive',
            name='waiting_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job_archive',
            name='year_arch',
            field=models.IntegerField(default=0),
        ),
    ]
