# Generated by Django 3.0.5 on 2021-01-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20210121_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_archive',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
