# Generated by Django 3.0.5 on 2021-02-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_archive_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_archive',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
